/* DPR export — a printable bank-format document (the browser's own
   Save-as-PDF) and a CSV for anyone who wants the numbers in Excel.

   No new dependencies, matching how reports/reportService.js already exports.
   Unlike that one, every interpolated value is HTML-escaped here: a DPR is
   built almost entirely from free-text the farmer typed (names, village,
   purpose), so unescaped output would break the document on an innocent "&"
   in a village name — quite apart from being unsafe. */

import { buildDocument } from "./dprDocument.js";

const esc = (v) => String(v ?? "")
  .replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
  .replace(/"/g, "&quot;").replace(/'/g, "&#39;");

const VERDICT_TEXT = {
  strong:     "All key ratios clear the usual appraisal norms.",
  viable:     "Key ratios are within acceptable appraisal norms.",
  weak:       "One or more key ratios fall short of the usual appraisal norms.",
  incomplete: "One or more ratios could not be computed from the figures given.",
};

/* ---------- printable document ---------- */

function sectionHtml(s) {
  if (s.text) return `<p class="narrative">${esc(s.text)}</p>`;
  if (s.rows) {
    return `<table class="kv">${s.rows.map((r) =>
      `<tr><td class="k">${esc(r.label)}</td><td class="v">${esc(r.value)}</td></tr>`).join("")}</table>`;
  }
  const { headers, data, total } = s.table;
  return `<table class="grid">
    <thead><tr>${headers.map((h) => `<th>${esc(h)}</th>`).join("")}</tr></thead>
    <tbody>${data.map((row) =>
      `<tr>${row.map((c) => `<td>${esc(c)}</td>`).join("")}</tr>`).join("")}</tbody>
    ${total ? `<tfoot><tr>${total.map((c) => `<th>${esc(c)}</th>`).join("")}</tr></tfoot>` : ""}
  </table>`;
}

export function toHtml(doc) {
  return `<!doctype html><html><head><meta charset="utf-8"><title>${esc(doc.title)}</title><style>
    @page { size: A4; margin: 18mm 14mm; }
    * { box-sizing: border-box; }
    body { font-family: system-ui, -apple-system, "Segoe UI", sans-serif; color: #12211A; margin: 0; font-size: 12px; line-height: 1.45; }
    header { border-bottom: 2px solid #12211A; padding-bottom: 10px; margin-bottom: 18px; }
    h1 { font-size: 19px; margin: 0 0 4px; }
    .sub { font-size: 12px; color: #444; }
    .meta { font-size: 10.5px; color: #777; margin-top: 6px; }
    h2 { font-size: 13px; margin: 20px 0 6px; padding-bottom: 3px; border-bottom: 1px solid #bbb; page-break-after: avoid; }
    table { border-collapse: collapse; width: 100%; margin-top: 4px; page-break-inside: avoid; }
    td, th { border: 1px solid #ccc; padding: 5px 7px; text-align: left; vertical-align: top; }
    th { background: #f1f4f2; font-weight: 600; }
    table.kv td.k { width: 42%; color: #444; }
    table.kv td.v { font-weight: 600; }
    table.grid td:not(:nth-child(2)), table.grid th:not(:nth-child(2)) { text-align: right; }
    table.grid td:first-child, table.grid th:first-child { text-align: left; }
    tfoot th { background: #e6ece8; }
    .narrative { margin: 6px 0; white-space: pre-wrap; }
    .verdict { margin: 14px 0 0; padding: 9px 11px; border-left: 4px solid #12211A; background: #f5f8f6; font-size: 11.5px; }
    .disclaimer { margin-top: 22px; padding: 10px 12px; border: 1px solid #d3b26a; background: #fdf8ec; font-size: 10.5px; page-break-inside: avoid; }
    .sign { margin-top: 34px; display: flex; justify-content: space-between; page-break-inside: avoid; }
    .sign div { width: 42%; border-top: 1px solid #555; padding-top: 5px; font-size: 11px; text-align: center; }
    footer { margin-top: 26px; border-top: 1px solid #ddd; padding-top: 7px; font-size: 10px; color: #888; }
  </style></head><body>
    <header>
      <h1>${esc(doc.title)}</h1>
      <div class="sub">Detailed Project Report${doc.applicant ? ` — ${esc(doc.applicant)}` : ""}</div>
      <div class="meta">Generated by AgriOS India on ${esc(doc.generatedAt)}</div>
    </header>
    ${doc.sections.map((s) => `<h2>${esc(s.heading)}</h2>${sectionHtml(s)}`).join("")}
    ${doc.verdict ? `<div class="verdict"><b>Appraisal summary:</b> ${esc(VERDICT_TEXT[doc.verdict.level] || "")}</div>` : ""}
    <div class="disclaimer"><b>Disclaimer.</b> ${esc(doc.disclaimer)}</div>
    <div class="sign"><div>Signature of applicant</div><div>Date &amp; place</div></div>
    <footer>Prepared with AgriOS India · Figures are the applicant's own and require verification against the financing bank's current unit-cost norms.</footer>
  </body></html>`;
}

/* Opens a print window. Returns false when the browser blocked the popup, so
   the caller can tell the farmer why nothing happened instead of failing mute. */
export function printDpr(input, computed, now = new Date()) {
  const doc = buildDocument(input, computed, now);
  const w = window.open("", "_blank");
  if (!w) return false;
  w.document.write(toHtml(doc));
  w.document.close();
  w.focus();
  w.print();
  return true;
}

/* ---------- CSV ---------- */

export function toCsv(input, computed, now = new Date()) {
  const doc = buildDocument(input, computed, now);
  const q = (v) => `"${String(v ?? "").replace(/"/g, '""')}"`;
  const lines = [q(doc.title), q(`Generated: ${doc.generatedAt}`), ""];

  doc.sections.forEach((s) => {
    lines.push(q(s.heading));
    if (s.text) lines.push(q(s.text));
    if (s.rows) s.rows.forEach((r) => lines.push(`${q(r.label)},${q(r.value)}`));
    if (s.table) {
      lines.push(s.table.headers.map(q).join(","));
      s.table.data.forEach((row) => lines.push(row.map(q).join(",")));
      if (s.table.total) lines.push(s.table.total.map(q).join(","));
    }
    lines.push("");
  });

  lines.push(q("Disclaimer"), q(doc.disclaimer));
  return lines.join("\r\n");
}

export function downloadCsv(input, computed, now = new Date()) {
  const csv = toCsv(input, computed, now);
  const name = (input.project?.title || input.name || "DPR").replace(/[^\w\s-]/g, "").trim().replace(/\s+/g, "_");
  // BOM so Excel opens the ₹ sign and Indian names in the right encoding.
  const blob = new Blob(["﻿" + csv], { type: "text/csv;charset=utf-8" });
  const a = document.createElement("a");
  a.href = URL.createObjectURL(blob);
  a.download = `${name}_DPR.csv`;
  a.click();
  URL.revokeObjectURL(a.href);
}
