/* Non-shell icon registry — loaded via dynamic import() from Icon.jsx.
   Icons used only in lazy screens live here; shell-critical icons stay in Icon.jsx. */
export {
  X, Check, AlertCircle, RotateCcw, Inbox, Wrench, SearchX,
  House, LayoutGrid, User, Store, Settings, LogOut,
  Sprout, Wheat, Milk, Bird, Rabbit, PiggyBank, Fish, Bug, Leaf, Package,
  Stethoscope, Calculator, Scale, Landmark, LineChart, CalendarDays,
  Briefcase, MessageCircle, TrendingUp, TrendingDown, BarChart3, Users, ShoppingBag,
  Tractor, Pill, FlaskConical, Send, GraduationCap, Building2, ShieldCheck, Truck,
  Crown, CreditCard, FileText, LifeBuoy, Lock, CloudRain,
  ArrowDownLeft, ArrowUpRight, Camera, Newspaper, Moon, SmartphoneNfc,
  SlidersHorizontal, Wallet, Mic, Volume2, Star, Trash2,
  Cloud, CloudFog, CloudDrizzle, CloudLightning, Snowflake, Umbrella,
  Thermometer, Gauge, Navigation, Compass, Plus, RefreshCw,
  Clock, SprayCan, Timer, CameraOff, ImagePlus, FlipHorizontal2, Aperture, Zap,
  BookmarkPlus, BookmarkCheck, ExternalLink, BadgeCheck, BadgeAlert, Lightbulb,
  Receipt, PlusCircle, ArrowDownCircle, ArrowUpCircle, BellOff,
  HeartPulse, Scan, ClipboardList, FileDown, History, Share2, Printer, GitBranch,
  Database, GitMerge, Activity, BarChart2, Layers, Package2, Cpu, Boxes,
  PieChart, Target, Crosshair, Radio, Network, ShieldAlert,
  XCircle, PlayCircle, PauseCircle, StopCircle, Hourglass,
  ArrowRight, ArrowLeft, ChevronUp, Eye, EyeOff, Tag, FolderOpen,
  Upload, Link, Unlink, Workflow, Server, HardDrive,
  LayoutDashboard, ListFilter, SortAsc, SortDesc, Pencil, Copy, MoreHorizontal,
  Syringe, Egg, BookOpen, ArrowLeftRight, Percent, Warehouse, Map, ClipboardCheck,
  ListChecks, CalendarClock, Banknote, Handshake, Contact, Factory, UserCheck,
  Satellite, Beef, Heart, ShoppingCart, Minus,
  Container, Gavel, FileSignature, IndianRupee, Route, Fuel, Calendar,
  BrainCircuit, Flame, PackageX, Dot,
  PanelLeftOpen, PanelLeftClose, ToggleLeft, CalendarCheck, GripVertical, GitCompare, Award,
  Fingerprint, MailOpen, UserPlus, UserX,
  Pin, PinOff, CornerUpLeft, SmilePlus,
  Paperclip, Video,
} from "lucide-react";
